import '../globals.scss';
import type { Metadata } from 'next';
import { Montserrat } from 'next/font/google';
import { Header, Footer } from '../../components';
// import { notFound } from 'next/navigation';

const montserrat = Montserrat({ subsets: ['latin'] });
const locales = ['en', 'ru'];

export const metadata: Metadata = {
	title: 'Max Rudin',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	params: { locale },
}: {
	children: React.ReactNode;
	params: any;
}) {
	const isValidLocale = locales.some((cur) => cur === locale);
	// if (!isValidLocale) notFound();

	return (
		<html lang={locale}>
			<body className={montserrat.className}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	);
}
